#Question 4:
#We have a function given below which prints an element from the list. But what if the user calls an invalid index? So, I want you to re-write the following function using the try-except block to handle the IndexError exception.
lst = ['Alice', 'Bob', 'Carl']
print(lst[3])